# Unity and Remix use separate graphics devices on the same GPU.
# Reduce unused space in partially occupied allocation blocks.
dxvk.deviceLocalMemoryChunkSizeMB = 64
dxvk.otherMemoryChunkSizeMB = 32
