using System.Reflection;
using BepInEx.Configuration;
using UnityEngine;
using UnityRemix.Legacy;
using Object = UnityEngine.Object;

int checks = 0;
void Check(bool condition, string message) { if (!condition) throw new Exception(message); checks++; }
void Call(LegacyPlugin plugin, string method) => typeof(LegacyPlugin).GetMethod(method, BindingFlags.NonPublic | BindingFlags.Instance)!.Invoke(plugin, null);
Material Make(string shader) => new Material("Shader \"" + shader + "\" {}") { mainTexture = new Texture2D() };
LegacyPlugin Begin() { var p = new LegacyPlugin(); Call(p, "Awake"); Call(p, "Start"); return p; }
void Frame(LegacyPlugin p) { Time.realtimeSinceStartup += 1.1f; Call(p, "Update"); Check(p.Logger.Errors.Count == 0, "Plugin reported an error"); }
try
{
    foreach (var name in new[] { "UI/Default", "GUI/Text Shader", "Hidden/Internal", "Skybox/Cubemap", "UnityRemix/Legacy/Opaque", "" })
        Check(!LegacyMaterialPolicy.ShouldConvert(name), "UI/engine shaders must remain original");
    Check(LegacyMaterialPolicy.Classify("Transparent/Cutout/Diffuse", "", 3000) == MaterialMode.Cutout, "Cutout takes precedence over queue");
    Check(LegacyMaterialPolicy.Classify("Particles/Additive", "", 3000) == MaterialMode.Additive, "Additive particles");
    Check(LegacyMaterialPolicy.Classify("Custom", "Transparent", 2000) == MaterialMode.Transparent, "Custom render type");
    Check(!LegacyMaterialPolicy.ShouldConvert("VolumetricFog2/VolumetricFog2DURP"), "Fog bounds cannot become an opaque converted material");
    foreach (var alias in new[] { "_Albedo", "_Albdeo", "_BaseColor_T", "_Basecolor", "_CandleSprite", "_Albedo1" })
    {
        var custom = Make("Custom/Surface"); custom.Properties = new() { alias, "_Colour" };
        var tex = new Texture2D(); custom.SetTexture(alias, tex); custom.SetColor("_Colour", new(.1f,.3f,.7f,.5f));
        var target = Make("UnityRemix/Legacy/Opaque");
        LegacyMaterialProperties.Copy(custom, target, null, false);
        Check(target.mainTexture == tex && target.color == custom.GetColor("_Colour"), "Shared texture/color aliases survive legacy conversion: " + alias);
    }
    var original = Make("Diffuse");
    var r1 = new Renderer { sharedMaterials = new[] { original } };
    var r2 = new Renderer { sharedMaterials = new[] { original } };
    var plugin = Begin(); Frame(plugin);
    var adapted = r1.sharedMaterials[0];
    Check(adapted != original && adapted == r2.sharedMaterials[0], "Shared original has one owned conversion");
    Check(adapted.mainTexture == original.mainTexture, "Texture storage shared with Unity");
    var newTexture = new Texture2D(); original.mainTexture = newTexture; original.color = new(.2f,.3f,.4f,.5f);
    Frame(plugin);
    Check(adapted.mainTexture == newTexture && adapted.color == original.color, "Original material animation reaches conversion");
    adapted.color = new(.1f,.2f,.3f,.25f); Frame(plugin);
    Check(adapted.color.A == .25f, "Game animation on the assigned material is not reset by an unchanged original");
    r1.sharedMaterials = new[] { adapted, Make("GUI/Text Shader") };
    Frame(plugin); r2.enabled = false; Frame(plugin);
    Check(r2.sharedMaterials[0] == original, "Disabled renderer restored");
    for (int i = 0; i < 4; i++) Frame(plugin);
    Check(!adapted.Destroyed && r1.sharedMaterials[0] == adapted, "Growing a material array cannot retire a live conversion");
    var replacement = Make("Custom/New"); r1.sharedMaterials = new[] { replacement };
    Call(plugin, "Shutdown");
    Check(r1.sharedMaterials[0] == replacement && !replacement.Destroyed, "Shutdown preserves a game-side replacement");
    Check(adapted.Destroyed && !original.Destroyed && !newTexture.Destroyed, "Shutdown destroys only owned materials");
    Object.World.Clear();
    original = Make("Diffuse"); r1 = new Renderer { sharedMaterials = new[] { original } };
    plugin = Begin(); Frame(plugin); adapted = r1.sharedMaterials[0];
    original.shader = new Shader { name = "UI/Default" }; Frame(plugin);
    Check(r1.sharedMaterials[0].shader.name.EndsWith("/UI"), "Changing to UI shader switches to raster pass");
    original.shader = new Shader { name = "Transparent/Cutout/Diffuse" }; Frame(plugin);
    Check(r1.sharedMaterials[0].shader.name.EndsWith("Cutout"), "Changed shader updates material mode");
    ((ConfigEntry<bool>)plugin.Config.Entries["ConvertWorldMaterials"]).Value = false; Frame(plugin);
    Check(r1.sharedMaterials[0] == original, "Disabling conversion restores renderer");
    Screen.lockCursor = true; Screen.showCursor = false; LegacyBridge.Open = true; Call(plugin, "LateUpdate");
    Check(!Screen.lockCursor && Screen.showCursor, "Native menu can use cursor");
    LegacyBridge.Open = false; Call(plugin, "LateUpdate");
    Check(Screen.lockCursor && !Screen.showCursor, "Cursor state restored");
    var tiny = new Texture2D { width = 2, height = 2 }; var atlas = new Texture2D();
    var g1 = new UnityEngine.UI.Graphic { mainTexture = tiny, material = original };
    var g2 = new UnityEngine.UI.Graphic { mainTexture = atlas, material = original };
    Frame(plugin); Frame(plugin);
    Check(!LegacyBridge.Tagged.Contains(tiny.GetNativeTexturePtr()) && !LegacyBridge.Tagged.Contains(atlas.GetNativeTexturePtr()), "Shared UI/world atlases are never globally tagged");
    var marker = Object.FindObjectsOfType<Texture>().Single(t=>t.name == "UnityRemix draw texture 1");
    Check(marker != null && LegacyBridge.Tagged.Contains(marker.GetNativeTexturePtr()), "Only the owned draw marker identifies UI");
    Check(g1.material == original && g2.material == original && g1.mainTexture == tiny && g2.mainTexture == atlas, "Canvas preserves original materials and individual font/sprite atlases");
    Check(LegacyBridge.Categories[3].Contains(tiny.GetNativeTexturePtr()) && LegacyBridge.Categories[3].Contains(atlas.GetNativeTexturePtr()), "Canvas textures use the category qualified by screen-space depth state");
    Call(plugin, "Shutdown");
    Check(g1.material == original && marker.Destroyed && !atlas.Destroyed, "UI restore releases only owned resources");
    Object.World.Clear();
    original = Make("Diffuse"); r1 = new Renderer { sharedMaterials = new[] { original } };
    plugin = Begin(); ((ConfigEntry<int>)plugin.Config.Entries["MaxConvertedMaterials"]).Value = 1;
    Frame(plugin); adapted = r1.sharedMaterials[0];
    replacement = Make("Custom/Replacement"); r1.sharedMaterials = new[] { replacement };
    for (int i = 0; i < 5; i++) Frame(plugin);
    Check(adapted.Destroyed && r1.sharedMaterials[0] != replacement, "A full material budget recovers after a game replaces its material");
    adapted = r1.sharedMaterials[0]; r1.sharedMaterials = new Material[] { null };
    for (int i = 0; i < 5; i++) Frame(plugin);
    Check(adapted.Destroyed, "Empty material slots release their cached conversion");
    Call(plugin, "Shutdown");
    Object.World.Clear();
    original = Make("Custom/NoLightMap"); original.Properties = new() { "_node_8550", "_Colorr", "_Ref" };
    var customTexture = new Texture2D(); original.SetTexture("_node_8550", customTexture);
    original.SetTextureScale("_node_8550", new(3,4)); original.SetTextureOffset("_node_8550", new(.1f,.2f));
    original.SetColor("_Colorr", new(.2f,.6f,.8f,.7f)); original.SetFloat("_Ref", 3);
    var converted = Make("UnityRemix/Legacy/Opaque");
    LegacyMaterialProperties.Copy(original, converted, new Texture2D(), false);
    Check(converted.mainTexture == customTexture && converted.mainTextureScale == new Vector2(3,4) && converted.mainTextureOffset == new Vector2(.1f,.2f), "Sonic custom albedo and UV transform survive conversion");
    Check(converted.color == original.GetColor("_Colorr") && converted.GetFloat("_Stencil") == 3 && converted.GetFloat("_StencilComp") == 3, "Custom tint and stencil portal reference survive");
    Check(LegacyMaterialProperties.CullMode("Transparent/Cutout/VertexLit") == 0 && LegacyMaterialProperties.CullMode("FX/Diamond") == 1, "Double-sided and front-culled effects retain culling");
    Check(LegacyMaterialPolicy.Classify("Particles/Alpha Blended Premultiply", "", 3000) == MaterialMode.Premultiplied, "Premultiplied particles preserve blending");
    Check(LegacyMaterialPolicy.Classify("Custom/Discard", "", 2000) == MaterialMode.Discard, "Discard effects never become opaque");
    r1 = new Renderer { sharedMaterials = new[] { original } };
    var uiGraphic = new UnityEngine.UI.Graphic { material = original, mainTexture = customTexture };
    var dome = new Renderer { name = "skydome", sharedMaterials = new[] { Make("Shader Forge/VertexColor") } };
    var waterSource = Make("Custom/Water"); waterSource.Properties.Add("_SeaColor"); waterSource.SetColor("_SeaColor", new(.1f,.3f,.5f,.8f));
    var water = new Renderer { sharedMaterials = new[] { waterSource } };
    var skybox = Make("RenderFX/Skybox"); skybox.Properties.Add("_FrontTex"); var sunFace = new Texture2D(); skybox.SetTexture("_FrontTex", sunFace); RenderSettings.skybox = skybox;
    plugin = Begin(); Frame(plugin);
    Check(r1.sharedMaterials[0] != uiGraphic.material && r1.sharedMaterials[0].shader.name.EndsWith("Opaque"), "One original material can serve separate world and UI roles");
    Check(dome.sharedMaterials[0].shader.name.EndsWith("Sky") && dome.sharedMaterials[0].renderQueue == 1000, "Untextured sky domes use the sky path");
    Check(water.sharedMaterials[0].shader.name.EndsWith("Water") && water.sharedMaterials[0].color == waterSource.GetColor("_SeaColor"), "Ocean retains sea color in its separate water pass");
    Check(water.sharedMaterials[0].GetTexture("_UnityRemixCategory") != dome.sharedMaterials[0].GetTexture("_UnityRemixCategory"), "Sky and water have distinct draw markers");
    Check(!LegacyBridge.Tagged.Contains(customTexture.GetNativeTexturePtr()), "World texture shared with UI stays out of global UI category");
    Check(RenderSettings.skybox == skybox && skybox.GetTexture("_FrontTex") == sunFace && LegacyBridge.Categories[1].Contains(sunFace.GetNativeTexturePtr()), "Original skybox and emissive sun face remain intact and receive sky classification");
    RenderSettings.skybox = null;
    Call(plugin, "Shutdown");
    Object.World.Clear();
    var cameraSky = Make("ThirdParty/Atmosphere");
    cameraSky.Properties.Add("_Tex"); var cubeTexture = new Cubemap(); cameraSky.SetTexture("_Tex", cubeTexture);
    var skyCamera = new Skybox { material = cameraSky };
    var cameraDome = new Renderer { sharedMaterials = new[] { cameraSky } };
    var procedural = Make("ThirdParty/CloudSimulation"); procedural.RenderType = "Background";
    procedural.Properties.Add("_Exposure"); procedural.SetFloat("_Exposure", 3.5f);
    var proceduralDome = new Renderer { sharedMaterials = new[] { procedural } };
    var reflecting = Make("Reflective/Cubemap"); reflecting.Properties.Add("_Cubemap"); reflecting.SetTexture("_Cubemap", cubeTexture);
    var reflectiveMesh = new Renderer { sharedMaterials = new[] { reflecting } };
    plugin = Begin(); Frame(plugin); Frame(plugin);
    Check(cameraDome.sharedMaterials[0] == cameraSky && skyCamera.material == cameraSky, "Camera sky context preserves an unfamiliar shader on a sky mesh");
    Check(LegacyBridge.Categories[1].Contains(cubeTexture.GetNativeTexturePtr()), "Cubemap sky slot is tagged without conversion to a 2D texture");
    Check(proceduralDome.sharedMaterials[0] == procedural && procedural.GetFloat("_Exposure") == 3.5f, "Procedural background preserves its shader and exposure");
    Check(reflectiveMesh.sharedMaterials[0].shader.name.EndsWith("Opaque"), "Reflective world material is not mistaken for a sky because it has a cubemap");
    var panorama = Make("Skybox/Panoramic"); panorama.SetFloat("_Exposure", 2);
    var panoramaTexture = panorama.mainTexture; skyCamera.material = panorama;
    for (int i = 0; i < 4; i++) Frame(plugin);
    Check(skyCamera.material == panorama && LegacyBridge.Categories[1].Contains(panoramaTexture.GetNativeTexturePtr()), "Live camera sky changes discover a panoramic texture without replacing the shader");
    var ocean = Make("Ocean/Indie/OceanShader"); ocean.Properties = new() { "_SkyBox", "_SeaColor" }; ocean.mainTexture = null;
    var oceanReflection = new Cubemap(); ocean.SetTexture("_SkyBox", oceanReflection); ocean.SetColor("_SeaColor", new(.06f,.29f,.39f,1));
    var oceanRenderer = new Renderer { sharedMaterials = new[] { ocean } };
    Frame(plugin); Frame(plugin);
    Check(oceanRenderer.sharedMaterials[0] == ocean && ocean.mainTexture == null, "Procedural ocean keeps its original shader instead of receiving a blank albedo");
    Check(LegacyBridge.WaterMaterials[oceanReflection.GetNativeTexturePtr()] == (ocean.GetColor("_SeaColor"), 1.333f), "Ocean color and IOR are registered for the path-traced material");
    ocean.SetColor("_SeaColor", new(.12f,.24f,.48f,1)); Frame(plugin); Frame(plugin);
    Check(LegacyBridge.WaterMaterials[oceanReflection.GetNativeTexturePtr()].Color == ocean.GetColor("_SeaColor"), "Live water color changes update native material metadata");
    Call(plugin, "Shutdown");
    Check(!cubeTexture.Destroyed && !panoramaTexture.Destroyed, "Sky teardown retains game-owned cubemaps and panorama textures");
    Object.World.Clear();
    var lighting = new LegacyLighting(); lighting.Update(true, 1);
    var fallback = Object.FindObjectsOfType<Light>().Single();
    Check(fallback.enabled && fallback.type == LightType.Directional, "A scene without a sun receives one fallback directional light");
    var realSun = new Light { type = LightType.Directional, intensity = 2 };
    lighting.Update(true, 1);
    Check(!fallback.enabled && lighting.DirectionalCount == 1 && realSun.intensity == 2, "A game sun disables the fallback without changing authored intensity");
    realSun.enabled = false; lighting.Update(true, 1);
    Check(fallback.enabled, "Fallback tracks scene light changes");
    lighting.Shutdown(); Check(fallback.gameObject.Destroyed && !realSun.gameObject.Destroyed, "Light cleanup preserves the game's lights");
    Console.WriteLine($"PASS: {checks} legacy material ownership, UI, and classification checks.");
    return 0;
}
catch (Exception error) { Console.Error.WriteLine(error); return 1; }
